project:
  type: book
  output-dir: docs/
  
freeze: false

execute:
  warning: false
  message: false
  cache: false


book:
  title: "The Logic of Experiments"
  author: "Carlisle Rainey"
  chapters:
    - index.qmd
    - ch/ate.qmd
    - ch/ate-hat.qmd
    - ch/var.qmd
    #- ch/var-est.qmd
    - part: "Appendices"
      chapters:
        - appendices/var-proof.qmd

bibliography: references.bib

format:
  html:
    theme:
      - journal
      - brand
    css: _styles.css
    citation-location: margin
    reference-location: margin




